version: '3'

services:
  # Nginx
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx/html:/usr/share/nginx/html
      - /opt/nginx/logs:/var/log/nginx
      - /opt/nginx/conf:/etc/nginx
    restart: always

  # Redis
  redis:
    image: redis:6.0.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /opt/redis/redis.conf:/etc/redis/redis.conf
      - /opt/redis/data:/data
      - /opt/redis/logs:/logs
    environment:
      TZ: Asia/Shanghai
    command: [ redis-server, --requirepass, 密码 ]
    restart: always