version: '3'

services:
  # Nginx
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/project/nginx/html:/usr/share/nginx/html
      - /opt/project/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/project/nginx/conf.d:/etc/nginx/conf.d
      - /opt/project/nginx/log:/var/log/nginx
      - /opt/project/nginx/ssl/ssl.conf:/etc/nginx/ssl/ssl.conf
      - /opt/project/nginx/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem
      - /opt/project/nginx/letsencrypt:/etc/nginx/letsencrypt
    restart: always

  # MinIO
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /opt/minio/data:/data
      - /opt/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: 登陆账号
      MINIO_SECRET_KEY: 登录密码
    command: server /data --console-address ":9001"
    restart: always

