version: '3'

services:
  # Nginx
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/nginx/html/pc:/usr/share/nginx/html
      - /opt/nginx/html/mobile:/usr/share/nginx/html
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx/conf.d:/etc/nginx/conf.d
      - /opt/nginx/log:/var/log/nginx
    restart: always

  # Redis
  redis:
    image: redis:6.0.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /opt/project/redis/redis.conf:/etc/redis/redis.conf
      - /opt/project/redis/data:/data
      - /opt/project/redis/logs:/logs
    environment:
      TZ: Asia/Shanghai
    command: [ redis-server, --requirepass, 密码 ]
    restart: always

  # MinIO
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /opt/minio/data:/data
      - /opt/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: 登陆账号
      MINIO_SECRET_KEY: 登录密码
    command: server /data --console-address ":9001"
    restart: always

