version: '3'

services:
  # Nginx
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/project/nginx/html:/usr/share/nginx/html
      - /opt/project/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/project/nginx/conf.d:/etc/nginx/conf.d
      - /opt/project/nginx/log:/var/log/nginx
      - /opt/project/nginx/ssl/ssl.conf:/etc/nginx/ssl/ssl.conf
      - /opt/project/nginx/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem
      - /opt/project/nginx/letsencrypt:/etc/nginx/letsencrypt
    restart: always

  # ElasticSearch
  elasticsearch:
    image: elasticsearch:7.17.4
    volumes:
      - /etc/localtime:/etc/localtime
      - /es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /es/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - '9200:9200'
      - '9300:9300'
    container_name: elasticsearch
    environment:
      - 'cluster.name=elasticsearch' #设置集群名称为elasticsearch
      - 'discovery.type=single-node' #以单一节点模式启动
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m' #设置使用jvm内存大小
    restart: always

  # Kibana
  kibana:
    image: kibana:7.17.4
    container_name: kibana
    volumes:
      - /etc/localtime:/etc/localtime
      - /kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - '5601:5601'
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200 #设置访问elasticsearch的地址
      - 'elasticsearch.hosts=http://es:9200' #设置访问elasticsearch的地址
      - I18N_LOCALE=zh-CN
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

  # Prometheus

  # Grafana

