spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/quick_chat?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456
    doris:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:9527/quick_chat_doris?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: 账号
      password: 密码
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
        max-active: 20
  mail:
    host: smtp.qq.com
    port: 465
    username: 1262254123@qq.com
    password: ocebnufztunlbagc
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
rocketmq:
  consumer:
    group: springboot_consumer_group
    pull-batch-size: 10
  name-server: localhost:9876
  producer:
    group: springboot_producer_group
    sendMessageTimeout: 10000
    retryTimesWhenSendFailed: 2
    retryTimesWhenSendAsyncFailed: 2
    maxMessageSize: 4096
    compressMessageBodyThreshold: 4096
    retryNextServer: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
logging:
  level:
    RocketmqClient: ERROR
    io:
    netty: ERROR
xxl:
  job:
    admin:
      addresses: 127.0.0.1
    accessToken: "Mock Token"
    executor:
      appname: "AppName"
      address: "Address"
      ip: "IP"
      port: 9001
      logpath: /opt/project/backend/myLogs
      logretentiondays: 30
quick-chat:
  common-group-id: 1
  no-recall-time: 120
  voice-time-limit: 60
  session-size-limit: 50
  size:
    avatar: 2
    voice: 5
    file: 50
  group:
    size: 100
    invite-count: 20
  avatar:
    boy: https://xuzhibin-bucket.oss-cn-beijing.aliyuncs.com/QuickChat/boy.png
    girl: https://xuzhibin-bucket.oss-cn-beijing.aliyuncs.com/QuickChat/girl.png