version: '3'

services:
  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always

  # Kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 101.42.13.186
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://101.42.13.186:9092
      KAFKA_BROKER_ID: 1
    restart: always

  # JAR 8888
  backend-project-8888:
    image: backend-project
    container_name: backend-project
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - /opt/project/backend/myLogs:/myLogs
    restart: always

  # JAR 8889
  backend-project-8889:
    image: backend-project
    container_name: backend-project
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - /opt/project/backend/myLogs:/myLogs
    restart: always